// World Cup 2026 Sweepstake — data file.
// Edit results here, then refresh the page. See README.md for the schema.
window.WC_DATA = {
  "config": {
    "points": {
      "win": 3,
      "penWin": 2,
      "draw": 1,
      "loss": 0
    },
    "playerOrder": [
      "Dazzo",
      "Cones",
      "Burty",
      "Bilal",
      "Mr Nas"
    ],
    "eliminatedTeams": [],
    "unallocated": [
      "Haiti",
      "England",
      "Croatia"
    ],
    "live": {
      "enabled": true,
      "source": "espn",
      "url": "https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates=20260611-20260719&limit=400",
      "aliases": {
        "Bosnia-Herzegovina": "Bosnia and Herzegovina",
        "Congo DR": "DR Congo",
        "Türkiye": "Turkey",
        "Curaçao": "Curacao"
      }
    }
  },
  "teams": [
    {
      "name": "Mexico",
      "group": "A",
      "rank": 13
    },
    {
      "name": "South Africa",
      "group": "A",
      "rank": 61
    },
    {
      "name": "South Korea",
      "group": "A",
      "rank": 22
    },
    {
      "name": "Czechia",
      "group": "A",
      "rank": 43
    },
    {
      "name": "Canada",
      "group": "B",
      "rank": 31
    },
    {
      "name": "Bosnia and Herzegovina",
      "group": "B",
      "rank": 63
    },
    {
      "name": "Qatar",
      "group": "B",
      "rank": 56
    },
    {
      "name": "Switzerland",
      "group": "B",
      "rank": 19
    },
    {
      "name": "Brazil",
      "group": "C",
      "rank": 6
    },
    {
      "name": "Morocco",
      "group": "C",
      "rank": 7
    },
    {
      "name": "Haiti",
      "group": "C",
      "rank": 83
    },
    {
      "name": "Scotland",
      "group": "C",
      "rank": 40
    },
    {
      "name": "United States",
      "group": "D",
      "rank": 15
    },
    {
      "name": "Paraguay",
      "group": "D",
      "rank": 42
    },
    {
      "name": "Australia",
      "group": "D",
      "rank": 27
    },
    {
      "name": "Turkey",
      "group": "D",
      "rank": 23
    },
    {
      "name": "Germany",
      "group": "E",
      "rank": 10
    },
    {
      "name": "Curacao",
      "group": "E",
      "rank": 82
    },
    {
      "name": "Ivory Coast",
      "group": "E",
      "rank": 33
    },
    {
      "name": "Ecuador",
      "group": "E",
      "rank": 24
    },
    {
      "name": "Netherlands",
      "group": "F",
      "rank": 8
    },
    {
      "name": "Japan",
      "group": "F",
      "rank": 18
    },
    {
      "name": "Sweden",
      "group": "F",
      "rank": 38
    },
    {
      "name": "Tunisia",
      "group": "F",
      "rank": 45
    },
    {
      "name": "Belgium",
      "group": "G",
      "rank": 9
    },
    {
      "name": "Egypt",
      "group": "G",
      "rank": 29
    },
    {
      "name": "Iran",
      "group": "G",
      "rank": 20
    },
    {
      "name": "New Zealand",
      "group": "G",
      "rank": 85
    },
    {
      "name": "Spain",
      "group": "H",
      "rank": 2
    },
    {
      "name": "Cape Verde",
      "group": "H",
      "rank": 67
    },
    {
      "name": "Saudi Arabia",
      "group": "H",
      "rank": 60
    },
    {
      "name": "Uruguay",
      "group": "H",
      "rank": 17
    },
    {
      "name": "France",
      "group": "I",
      "rank": 3
    },
    {
      "name": "Senegal",
      "group": "I",
      "rank": 16
    },
    {
      "name": "Iraq",
      "group": "I",
      "rank": 57
    },
    {
      "name": "Norway",
      "group": "I",
      "rank": 30
    },
    {
      "name": "Argentina",
      "group": "J",
      "rank": 1
    },
    {
      "name": "Algeria",
      "group": "J",
      "rank": 28
    },
    {
      "name": "Austria",
      "group": "J",
      "rank": 25
    },
    {
      "name": "Jordan",
      "group": "J",
      "rank": 64
    },
    {
      "name": "Portugal",
      "group": "K",
      "rank": 5
    },
    {
      "name": "DR Congo",
      "group": "K",
      "rank": 46
    },
    {
      "name": "Uzbekistan",
      "group": "K",
      "rank": 50
    },
    {
      "name": "Colombia",
      "group": "K",
      "rank": 14
    },
    {
      "name": "England",
      "group": "L",
      "rank": 4
    },
    {
      "name": "Croatia",
      "group": "L",
      "rank": 11
    },
    {
      "name": "Ghana",
      "group": "L",
      "rank": 73
    },
    {
      "name": "Panama",
      "group": "L",
      "rank": 34
    }
  ],
  "players": {
    "Dazzo": [
      "Bosnia and Herzegovina",
      "Scotland",
      "Portugal",
      "Algeria",
      "South Korea",
      "Canada",
      "Argentina",
      "Tunisia",
      "Qatar"
    ],
    "Cones": [
      "Germany",
      "Spain",
      "Ghana",
      "New Zealand",
      "DR Congo",
      "Uruguay",
      "Czechia",
      "Norway",
      "Ecuador"
    ],
    "Burty": [
      "Belgium",
      "Jordan",
      "Australia",
      "France",
      "Austria",
      "Sweden",
      "Senegal",
      "Ivory Coast",
      "Egypt"
    ],
    "Bilal": [
      "South Africa",
      "Switzerland",
      "Colombia",
      "Saudi Arabia",
      "Morocco",
      "Panama",
      "Netherlands",
      "Uzbekistan",
      "Curacao"
    ],
    "Mr Nas": [
      "United States",
      "Iran",
      "Turkey",
      "Cape Verde",
      "Japan",
      "Iraq",
      "Mexico",
      "Brazil",
      "Paraguay"
    ]
  },
  "groupFixtures": [
    {
      "id": "G1",
      "group": "A",
      "matchday": 1,
      "home": "Mexico",
      "away": "South Africa",
      "date": "2026-06-11",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G2",
      "group": "A",
      "matchday": 1,
      "home": "South Korea",
      "away": "Czechia",
      "date": "2026-06-11",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G3",
      "group": "A",
      "matchday": 2,
      "home": "Mexico",
      "away": "South Korea",
      "date": "2026-06-18",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G4",
      "group": "A",
      "matchday": 2,
      "home": "Czechia",
      "away": "South Africa",
      "date": "2026-06-18",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G5",
      "group": "A",
      "matchday": 3,
      "home": "Mexico",
      "away": "Czechia",
      "date": "2026-06-24",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G6",
      "group": "A",
      "matchday": 3,
      "home": "South Africa",
      "away": "South Korea",
      "date": "2026-06-24",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G7",
      "group": "B",
      "matchday": 1,
      "home": "Canada",
      "away": "Bosnia and Herzegovina",
      "date": "2026-06-12",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G8",
      "group": "B",
      "matchday": 1,
      "home": "Qatar",
      "away": "Switzerland",
      "date": "2026-06-11",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G9",
      "group": "B",
      "matchday": 2,
      "home": "Canada",
      "away": "Qatar",
      "date": "2026-06-18",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G10",
      "group": "B",
      "matchday": 2,
      "home": "Switzerland",
      "away": "Bosnia and Herzegovina",
      "date": "2026-06-18",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G11",
      "group": "B",
      "matchday": 3,
      "home": "Canada",
      "away": "Switzerland",
      "date": "2026-06-24",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G12",
      "group": "B",
      "matchday": 3,
      "home": "Bosnia and Herzegovina",
      "away": "Qatar",
      "date": "2026-06-24",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G13",
      "group": "C",
      "matchday": 1,
      "home": "Brazil",
      "away": "Morocco",
      "date": "2026-06-13",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G14",
      "group": "C",
      "matchday": 1,
      "home": "Haiti",
      "away": "Scotland",
      "date": "2026-06-14",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G15",
      "group": "C",
      "matchday": 2,
      "home": "Brazil",
      "away": "Haiti",
      "date": "2026-06-19",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G16",
      "group": "C",
      "matchday": 2,
      "home": "Scotland",
      "away": "Morocco",
      "date": "2026-06-19",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G17",
      "group": "C",
      "matchday": 3,
      "home": "Brazil",
      "away": "Scotland",
      "date": "2026-06-24",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G18",
      "group": "C",
      "matchday": 3,
      "home": "Morocco",
      "away": "Haiti",
      "date": "2026-06-24",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G19",
      "group": "D",
      "matchday": 1,
      "home": "United States",
      "away": "Paraguay",
      "date": "2026-06-12",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G20",
      "group": "D",
      "matchday": 1,
      "home": "Australia",
      "away": "Turkey",
      "date": "2026-06-12",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G21",
      "group": "D",
      "matchday": 2,
      "home": "United States",
      "away": "Australia",
      "date": "2026-06-19",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G22",
      "group": "D",
      "matchday": 2,
      "home": "Turkey",
      "away": "Paraguay",
      "date": "2026-06-19",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G23",
      "group": "D",
      "matchday": 3,
      "home": "United States",
      "away": "Turkey",
      "date": "2026-06-25",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G24",
      "group": "D",
      "matchday": 3,
      "home": "Paraguay",
      "away": "Australia",
      "date": "2026-06-25",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G25",
      "group": "E",
      "matchday": 1,
      "home": "Germany",
      "away": "Curacao",
      "date": "2026-06-13",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G26",
      "group": "E",
      "matchday": 1,
      "home": "Ivory Coast",
      "away": "Ecuador",
      "date": "2026-06-13",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G27",
      "group": "E",
      "matchday": 2,
      "home": "Germany",
      "away": "Ivory Coast",
      "date": "2026-06-20",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G28",
      "group": "E",
      "matchday": 2,
      "home": "Ecuador",
      "away": "Curacao",
      "date": "2026-06-20",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G29",
      "group": "E",
      "matchday": 3,
      "home": "Germany",
      "away": "Ecuador",
      "date": "2026-06-25",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G30",
      "group": "E",
      "matchday": 3,
      "home": "Curacao",
      "away": "Ivory Coast",
      "date": "2026-06-25",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G31",
      "group": "F",
      "matchday": 1,
      "home": "Netherlands",
      "away": "Japan",
      "date": "2026-06-14",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G32",
      "group": "F",
      "matchday": 1,
      "home": "Sweden",
      "away": "Tunisia",
      "date": "2026-06-13",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G33",
      "group": "F",
      "matchday": 2,
      "home": "Netherlands",
      "away": "Sweden",
      "date": "2026-06-20",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G34",
      "group": "F",
      "matchday": 2,
      "home": "Tunisia",
      "away": "Japan",
      "date": "2026-06-20",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G35",
      "group": "F",
      "matchday": 3,
      "home": "Netherlands",
      "away": "Tunisia",
      "date": "2026-06-25",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G36",
      "group": "F",
      "matchday": 3,
      "home": "Japan",
      "away": "Sweden",
      "date": "2026-06-25",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G37",
      "group": "G",
      "matchday": 1,
      "home": "Belgium",
      "away": "Egypt",
      "date": "2026-06-14",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G38",
      "group": "G",
      "matchday": 1,
      "home": "Iran",
      "away": "New Zealand",
      "date": "2026-06-14",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G39",
      "group": "G",
      "matchday": 2,
      "home": "Belgium",
      "away": "Iran",
      "date": "2026-06-21",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G40",
      "group": "G",
      "matchday": 2,
      "home": "New Zealand",
      "away": "Egypt",
      "date": "2026-06-21",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G41",
      "group": "G",
      "matchday": 3,
      "home": "Belgium",
      "away": "New Zealand",
      "date": "2026-06-26",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G42",
      "group": "G",
      "matchday": 3,
      "home": "Egypt",
      "away": "Iran",
      "date": "2026-06-26",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G43",
      "group": "H",
      "matchday": 1,
      "home": "Spain",
      "away": "Cape Verde",
      "date": "2026-06-14",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G44",
      "group": "H",
      "matchday": 1,
      "home": "Saudi Arabia",
      "away": "Uruguay",
      "date": "2026-06-15",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G45",
      "group": "H",
      "matchday": 2,
      "home": "Spain",
      "away": "Saudi Arabia",
      "date": "2026-06-21",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G46",
      "group": "H",
      "matchday": 2,
      "home": "Uruguay",
      "away": "Cape Verde",
      "date": "2026-06-21",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G47",
      "group": "H",
      "matchday": 3,
      "home": "Spain",
      "away": "Uruguay",
      "date": "2026-06-26",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G48",
      "group": "H",
      "matchday": 3,
      "home": "Cape Verde",
      "away": "Saudi Arabia",
      "date": "2026-06-26",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G49",
      "group": "I",
      "matchday": 1,
      "home": "France",
      "away": "Senegal",
      "date": "2026-06-15",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G50",
      "group": "I",
      "matchday": 1,
      "home": "Iraq",
      "away": "Norway",
      "date": "2026-06-15",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G51",
      "group": "I",
      "matchday": 2,
      "home": "France",
      "away": "Iraq",
      "date": "2026-06-22",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G52",
      "group": "I",
      "matchday": 2,
      "home": "Norway",
      "away": "Senegal",
      "date": "2026-06-22",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G53",
      "group": "I",
      "matchday": 3,
      "home": "France",
      "away": "Norway",
      "date": "2026-06-26",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G54",
      "group": "I",
      "matchday": 3,
      "home": "Senegal",
      "away": "Iraq",
      "date": "2026-06-26",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G55",
      "group": "J",
      "matchday": 1,
      "home": "Argentina",
      "away": "Algeria",
      "date": "2026-06-16",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G56",
      "group": "J",
      "matchday": 1,
      "home": "Austria",
      "away": "Jordan",
      "date": "2026-06-16",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G57",
      "group": "J",
      "matchday": 2,
      "home": "Argentina",
      "away": "Austria",
      "date": "2026-06-22",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G58",
      "group": "J",
      "matchday": 2,
      "home": "Jordan",
      "away": "Algeria",
      "date": "2026-06-22",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G59",
      "group": "J",
      "matchday": 3,
      "home": "Argentina",
      "away": "Jordan",
      "date": "2026-06-27",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G60",
      "group": "J",
      "matchday": 3,
      "home": "Algeria",
      "away": "Austria",
      "date": "2026-06-27",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G61",
      "group": "K",
      "matchday": 1,
      "home": "Portugal",
      "away": "DR Congo",
      "date": "2026-06-16",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G62",
      "group": "K",
      "matchday": 1,
      "home": "Uzbekistan",
      "away": "Colombia",
      "date": "2026-06-16",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G63",
      "group": "K",
      "matchday": 2,
      "home": "Portugal",
      "away": "Uzbekistan",
      "date": "2026-06-23",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G64",
      "group": "K",
      "matchday": 2,
      "home": "Colombia",
      "away": "DR Congo",
      "date": "2026-06-23",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G65",
      "group": "K",
      "matchday": 3,
      "home": "Portugal",
      "away": "Colombia",
      "date": "2026-06-27",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G66",
      "group": "K",
      "matchday": 3,
      "home": "DR Congo",
      "away": "Uzbekistan",
      "date": "2026-06-27",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G67",
      "group": "L",
      "matchday": 1,
      "home": "England",
      "away": "Croatia",
      "date": "2026-06-17",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G68",
      "group": "L",
      "matchday": 1,
      "home": "Ghana",
      "away": "Panama",
      "date": "2026-06-17",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G69",
      "group": "L",
      "matchday": 2,
      "home": "England",
      "away": "Ghana",
      "date": "2026-06-23",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G70",
      "group": "L",
      "matchday": 2,
      "home": "Panama",
      "away": "Croatia",
      "date": "2026-06-23",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G71",
      "group": "L",
      "matchday": 3,
      "home": "England",
      "away": "Panama",
      "date": "2026-06-27",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    },
    {
      "id": "G72",
      "group": "L",
      "matchday": 3,
      "home": "Croatia",
      "away": "Ghana",
      "date": "2026-06-27",
      "city": "",
      "homeScore": null,
      "awayScore": null,
      "played": false
    }
  ],
  "knockoutFixtures": [
    {
      "id": "R32-1",
      "round": "R32",
      "gameNo": 1,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-06-28",
      "kickoff": "2026-06-28T19:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "A2",
      "srcAway": "B2"
    },
    {
      "id": "R32-2",
      "round": "R32",
      "gameNo": 2,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-06-29",
      "kickoff": "2026-06-29T17:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "C1",
      "srcAway": "F2"
    },
    {
      "id": "R32-3",
      "round": "R32",
      "gameNo": 3,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-06-30",
      "kickoff": "2026-06-30T01:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "F1",
      "srcAway": "C2"
    },
    {
      "id": "R32-4",
      "round": "R32",
      "gameNo": 4,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-06-29",
      "kickoff": "2026-06-29T20:30Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "E1",
      "srcAway": "3rd A/B/C/D/F"
    },
    {
      "id": "R32-5",
      "round": "R32",
      "gameNo": 5,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-06-30",
      "kickoff": "2026-06-30T17:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "E2",
      "srcAway": "I2"
    },
    {
      "id": "R32-6",
      "round": "R32",
      "gameNo": 6,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-01",
      "kickoff": "2026-07-01T01:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "A1",
      "srcAway": "3rd C/E/F/H/I"
    },
    {
      "id": "R32-7",
      "round": "R32",
      "gameNo": 7,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-06-30",
      "kickoff": "2026-06-30T21:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "I1",
      "srcAway": "3rd C/D/F/G/H"
    },
    {
      "id": "R32-8",
      "round": "R32",
      "gameNo": 8,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-01",
      "kickoff": "2026-07-01T20:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "G1",
      "srcAway": "3rd A/E/H/I/J"
    },
    {
      "id": "R32-9",
      "round": "R32",
      "gameNo": 9,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-02",
      "kickoff": "2026-07-02T00:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "D1",
      "srcAway": "3rd B/E/F/I/J"
    },
    {
      "id": "R32-10",
      "round": "R32",
      "gameNo": 10,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-01",
      "kickoff": "2026-07-01T16:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "L1",
      "srcAway": "3rd E/H/I/J/K"
    },
    {
      "id": "R32-11",
      "round": "R32",
      "gameNo": 11,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-02",
      "kickoff": "2026-07-02T23:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "K2",
      "srcAway": "L2"
    },
    {
      "id": "R32-12",
      "round": "R32",
      "gameNo": 12,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-02",
      "kickoff": "2026-07-02T19:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "H1",
      "srcAway": "J2"
    },
    {
      "id": "R32-13",
      "round": "R32",
      "gameNo": 13,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-03",
      "kickoff": "2026-07-03T03:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "B1",
      "srcAway": "3rd E/F/G/I/J"
    },
    {
      "id": "R32-14",
      "round": "R32",
      "gameNo": 14,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-03",
      "kickoff": "2026-07-03T18:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "D2",
      "srcAway": "G2"
    },
    {
      "id": "R32-15",
      "round": "R32",
      "gameNo": 15,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-03",
      "kickoff": "2026-07-03T22:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "J1",
      "srcAway": "H2"
    },
    {
      "id": "R32-16",
      "round": "R32",
      "gameNo": 16,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-04",
      "kickoff": "2026-07-04T01:30Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": null,
      "feedAway": null,
      "srcHome": "K1",
      "srcAway": "3rd D/E/I/J/L"
    },
    {
      "id": "R16-1",
      "round": "R16",
      "gameNo": 1,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-04",
      "kickoff": "2026-07-04T21:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R32-4",
      "feedAway": "R32-7",
      "srcHome": "Winner R32-4",
      "srcAway": "Winner R32-7"
    },
    {
      "id": "R16-2",
      "round": "R16",
      "gameNo": 2,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-04",
      "kickoff": "2026-07-04T17:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R32-1",
      "feedAway": "R32-3",
      "srcHome": "Winner R32-1",
      "srcAway": "Winner R32-3"
    },
    {
      "id": "R16-3",
      "round": "R16",
      "gameNo": 3,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-05",
      "kickoff": "2026-07-05T20:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R32-2",
      "feedAway": "R32-5",
      "srcHome": "Winner R32-2",
      "srcAway": "Winner R32-5"
    },
    {
      "id": "R16-4",
      "round": "R16",
      "gameNo": 4,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-06",
      "kickoff": "2026-07-06T00:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R32-6",
      "feedAway": "R32-10",
      "srcHome": "Winner R32-6",
      "srcAway": "Winner R32-10"
    },
    {
      "id": "R16-5",
      "round": "R16",
      "gameNo": 5,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-06",
      "kickoff": "2026-07-06T19:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R32-11",
      "feedAway": "R32-12",
      "srcHome": "Winner R32-11",
      "srcAway": "Winner R32-12"
    },
    {
      "id": "R16-6",
      "round": "R16",
      "gameNo": 6,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-07",
      "kickoff": "2026-07-07T00:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R32-9",
      "feedAway": "R32-8",
      "srcHome": "Winner R32-9",
      "srcAway": "Winner R32-8"
    },
    {
      "id": "R16-7",
      "round": "R16",
      "gameNo": 7,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-07",
      "kickoff": "2026-07-07T16:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R32-15",
      "feedAway": "R32-14",
      "srcHome": "Winner R32-15",
      "srcAway": "Winner R32-14"
    },
    {
      "id": "R16-8",
      "round": "R16",
      "gameNo": 8,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-07",
      "kickoff": "2026-07-07T20:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R32-13",
      "feedAway": "R32-16",
      "srcHome": "Winner R32-13",
      "srcAway": "Winner R32-16"
    },
    {
      "id": "QF-1",
      "round": "QF",
      "gameNo": 1,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-09",
      "kickoff": "2026-07-09T20:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R16-1",
      "feedAway": "R16-2",
      "srcHome": "Winner R16-1",
      "srcAway": "Winner R16-2"
    },
    {
      "id": "QF-2",
      "round": "QF",
      "gameNo": 2,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-10",
      "kickoff": "2026-07-10T19:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R16-5",
      "feedAway": "R16-6",
      "srcHome": "Winner R16-5",
      "srcAway": "Winner R16-6"
    },
    {
      "id": "QF-3",
      "round": "QF",
      "gameNo": 3,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-11",
      "kickoff": "2026-07-11T21:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R16-3",
      "feedAway": "R16-4",
      "srcHome": "Winner R16-3",
      "srcAway": "Winner R16-4"
    },
    {
      "id": "QF-4",
      "round": "QF",
      "gameNo": 4,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-12",
      "kickoff": "2026-07-12T01:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "R16-7",
      "feedAway": "R16-8",
      "srcHome": "Winner R16-7",
      "srcAway": "Winner R16-8"
    },
    {
      "id": "SF-1",
      "round": "SF",
      "gameNo": 1,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-14",
      "kickoff": "2026-07-14T19:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "QF-1",
      "feedAway": "QF-2",
      "srcHome": "Winner QF-1",
      "srcAway": "Winner QF-2"
    },
    {
      "id": "SF-2",
      "round": "SF",
      "gameNo": 2,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-15",
      "kickoff": "2026-07-15T19:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "QF-3",
      "feedAway": "QF-4",
      "srcHome": "Winner QF-3",
      "srcAway": "Winner QF-4"
    },
    {
      "id": "3P-1",
      "round": "3P",
      "gameNo": 1,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-18",
      "kickoff": "2026-07-18T21:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "SF-1",
      "feedAway": "SF-2",
      "srcHome": "Loser SF-1",
      "srcAway": "Loser SF-2"
    },
    {
      "id": "F-1",
      "round": "F",
      "gameNo": 1,
      "home": "TBD",
      "away": "TBD",
      "date": "2026-07-19",
      "kickoff": "2026-07-19T19:00Z",
      "homeScore": null,
      "awayScore": null,
      "decided": null,
      "winner": null,
      "played": false,
      "feedHome": "SF-1",
      "feedAway": "SF-2",
      "srcHome": "Winner SF-1",
      "srcAway": "Winner SF-2"
    }
  ]
};
